### PR TITLE
Feature update node packages to fix security alerts

### PR DESCRIPTION
**Pull request by jofomah**

### CODE REVIEW

**Comment by carsonreinke** [comment]
@jofomah still a WIP?

**Comment by jofomah** [comment]
@carsonreinke Yes, i still need to add tests if i understand the requirement correctly or are we skipping test setup, Travis Ci etc for now?

**Comment by carsonreinke** [comment]
@jofomah we don't need Travis to add a couple tests.

**Comment by jofomah** [comment]
@carsonreinke No longer a work in progress.

**Pull request merged**
